[package]
name = "libp2p-core"
version = "0.43.0"
edition = "2021"
description = "Core traits and types of libp2p"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"

[lib]
path = "src/lib.rs"

[dependencies]
# Dependencies are managed by the workspace
